version: '3.8'
networks:
  default:
    external:
      name: "dataclay-testing-network"
services:
  logicmodule:
    image: "bscdataclay/logicmodule:${JAVACLAY_IMAGE}"
    platform: ${IMAGE_PLATFORM}
    ports:
      - "12034:12034"
    command: ""
    environment:
      - LOGICMODULE_PORT_TCP=12034
      - LOGICMODULE_HOST=logicmodule
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      #- EXPOSED_IP_FOR_CLIENT=127.0.0.1
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
         
  dsjava:
    image: "bscdataclay/dsjava:${JAVACLAY_IMAGE}"
    platform: ${IMAGE_PLATFORM}
    ports:
      - "3127:3127"
    command: ""
    depends_on:
      - logicmodule
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=3127
      - LOGICMODULE_PORT_TCP=12034
      - LOGICMODULE_HOST=logicmodule
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dspython:
    image: "bscdataclay/dspython:${PYCLAY_IMAGE}"
    platform: ${IMAGE_PLATFORM}
    command: ""
    ports:
      - "6867:6867"
    depends_on:
      - logicmodule
      - dsjava
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=12034
      - LOGICMODULE_HOST=logicmodule
    stop_grace_period: 5m
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]